parameters:
#    uosuostms.example.class: uos\uostmsBundle\Example

services:
#    uosuostms.example:
#        class: %uosuostms.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
